# Generated by Django 2.1.7 on 2019-08-28 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=128, verbose_name='存储路径')),
                ('file_name', models.CharField(max_length=128, verbose_name='文件名')),
                ('update_time', models.DateTimeField(verbose_name='上传时间')),
                ('file_type', models.CharField(max_length=32, verbose_name='文件类型')),
                ('file_size', models.CharField(max_length=16, verbose_name='文件大小')),
                ('belong_folder', models.CharField(max_length=64, verbose_name='所属文件夹')),
                ('user', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FolderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(verbose_name='创建时间')),
                ('belong_folder', models.CharField(max_length=64, verbose_name='所属文件夹')),
                ('folder_name', models.CharField(max_length=64, verbose_name='文件夹名')),
                ('user', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
