# Generated by Django 2.1.7 on 2019-08-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=4096)),
                ('enmasterKey', models.CharField(max_length=4096)),
                ('enprivateKey', models.CharField(max_length=4096)),
                ('publicKey', models.CharField(max_length=4096)),
                ('token', models.CharField(max_length=4096)),
            ],
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='enfilekey',
            field=models.CharField(default=123, max_length=4096, verbose_name='EnFileKey'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='file_size',
            field=models.CharField(max_length=2048, verbose_name='文件大小'),
        ),
    ]
